/** 图标注册表 —— 数据层用字符串键引用,统一在此映射 */
import type { Component } from 'vue'
import {
  Anchor,
  Axe,
  Backpack,
  Bell,
  Bird,
  BookOpen,
  Castle,
  CircleDot,
  CircleUserRound,
  Cloud,
  Crown,
  Download,
  Droplets,
  Fish,
  Flame,
  FlaskConical,
  Footprints,
  Gem,
  Ghost,
  Hammer,
  HardHat,
  Home,
  Leaf,
  Link,
  Lock,
  Moon,
  Mountain,
  PawPrint,
  RefreshCw,
  Scroll,
  Settings,
  Shield,
  Shirt,
  Skull,
  Sparkles,
  Sprout,
  Star,
  Sunset,
  Sword,
  Swords,
  Trash2,
  Trees,
  Unlock,
  Upload,
  User,
  Wand,
  Watch,
  Waves,
  Wind,
  X,
  Zap,
  Umbrella
} from 'lucide-vue-next'

export const ICONS: Record<string, Component> = {
  anchor: Anchor,
  axe: Axe,
  backpack: Backpack,
  bell: Bell,
  bird: Bird,
  book: BookOpen,
  castle: Castle,
  'circle-dot': CircleDot,
  'circle-user': CircleUserRound,
  cloud: Cloud,
  crown: Crown,
  download: Download,
  droplets: Droplets,
  fish: Fish,
  flame: Flame,
  flask: FlaskConical,
  footprints: Footprints,
  gem: Gem,
  ghost: Ghost,
  hammer: Hammer,
  hardhat: HardHat,
  home: Home,
  leaf: Leaf,
  link: Link,
  lock: Lock,
  moon: Moon,
  mountain: Mountain,
  paw: PawPrint,
  refresh: RefreshCw,
  scroll: Scroll,
  settings: Settings,
  shield: Shield,
  shirt: Shirt,
  skull: Skull,
  sparkles: Sparkles,
  sprout: Sprout,
  star: Star,
  sunset: Sunset,
  sword: Sword,
  swords: Swords,
  trash: Trash2,
  trees: Trees,
  unlock: Unlock,
  upload: Upload,
  user: User,
  wand: Wand,
  watch: Watch,
  waves: Waves,
  wind: Wind,
  x: X,
  zap: Zap,
  umbrella: Umbrella
}

export function iconOf(name: string): Component {
  return ICONS[name] ?? Sparkles
}
